//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireEscape.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireEscape.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить фотографию в  протокол.
        /// </summary>
        internal static string AddPhotoError {
            get {
                return ResourceManager.GetString("AddPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить протокол.
        /// </summary>
        internal static string AddProtocolError {
            get {
                return ResourceManager.GetString("AddProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес объекта:.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите адрес объекта.
        /// </summary>
        internal static string AddressHint {
            get {
                return ResourceManager.GetString("AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес: .
        /// </summary>
        internal static string AddressStringFormat {
            get {
                return ResourceManager.GetString("AddressStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Escape.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поврежденные данные.
        /// </summary>
        internal static string BrokenData {
            get {
                return ResourceManager.GetString("BrokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте подключение к интернет и повторите операцию..
        /// </summary>
        internal static string CheckInternetMessage {
            get {
                return ResourceManager.GetString("CheckInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать файл отчета.
        /// </summary>
        internal static string CreateReportError {
            get {
                return ResourceManager.GetString("CreateReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представитель заказчика.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите представителя заказчика.
        /// </summary>
        internal static string CustomerHint {
            get {
                return ResourceManager.GetString("CustomerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить протокол?.
        /// </summary>
        internal static string DeleteProtocol {
            get {
                return ResourceManager.GetString("DeleteProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить протокол.
        /// </summary>
        internal static string DeleteProtocolError {
            get {
                return ResourceManager.GetString("DeleteProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отркдактировать параметры лестницы.
        /// </summary>
        internal static string EditFireEscapeError {
            get {
                return ResourceManager.GetString("EditFireEscapeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредактировать протокол.
        /// </summary>
        internal static string EditProtocolError {
            get {
                return ResourceManager.GetString("EditProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожарная лестница.
        /// </summary>
        internal static string FireEscape {
            get {
                return ResourceManager.GetString("FireEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите тип установки лестницы.
        /// </summary>
        internal static string FireEscapeMountTypesHint {
            get {
                return ResourceManager.GetString("FireEscapeMountTypesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер испытуемого объекта:.
        /// </summary>
        internal static string FireEscapeNum {
            get {
                return ResourceManager.GetString("FireEscapeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название объекта:.
        /// </summary>
        internal static string FireEscapeObject {
            get {
                return ResourceManager.GetString("FireEscapeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название объекта.
        /// </summary>
        internal static string FireEscapeObjectHint {
            get {
                return ResourceManager.GetString("FireEscapeObjectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры лестницы.
        /// </summary>
        internal static string FireEscapePageTitle {
            get {
                return ResourceManager.GetString("FireEscapePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите тип лестницы.
        /// </summary>
        internal static string FireEscapeTypesHint {
            get {
                return ResourceManager.GetString("FireEscapeTypesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить список протоколов.
        /// </summary>
        internal static string GetProtocolsError {
            get {
                return ResourceManager.GetString("GetProtocolsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить список пользователей.
        /// </summary>
        internal static string GetUserAccountsError {
            get {
                return ResourceManager.GetString("GetUserAccountsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место:.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите город / область.
        /// </summary>
        internal static string LocationHint {
            get {
                return ResourceManager.GetString("LocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список протоколов.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фотографию.
        /// </summary>
        internal static string MakePhotoHint {
            get {
                return ResourceManager.GetString("MakePhotoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый протокол.
        /// </summary>
        internal static string NewProtocol {
            get {
                return ResourceManager.GetString("NewProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет подключения.
        /// </summary>
        internal static string NoConnectivity {
            get {
                return ResourceManager.GetString("NoConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nophoto.png.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отредкатировать учетные записи пользователей.
        /// </summary>
        internal static string OpenUserAccountsPageError {
            get {
                return ResourceManager.GetString("OpenUserAccountsPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата протокола: .
        /// </summary>
        internal static string ProtocolDate {
            get {
                return ResourceManager.GetString("ProtocolDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер протокола:.
        /// </summary>
        internal static string ProtocolNum {
            get {
                return ResourceManager.GetString("ProtocolNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протокол.
        /// </summary>
        internal static string ProtocolPageTitle {
            get {
                return ResourceManager.GetString("ProtocolPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сохранить протокол.
        /// </summary>
        internal static string SaveProtocolError {
            get {
                return ResourceManager.GetString("SaveProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Незарегистрированная версия приложения. Сообщите номер {0} вендору приложения..
        /// </summary>
        internal static string UnregisteredApplicationMessage {
            get {
                return ResourceManager.GetString("UnregisteredApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string UserAccountsPageTitle {
            get {
                return ResourceManager.GetString("UserAccountsPageTitle", resourceCulture);
            }
        }
    }
}
